// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfARA9gYiFWDnz7EjjNLzkuhEjnOqGWSs',
    appId: '1:1060114483272:web:a79ab09c2abb8e9756f07d',
    messagingSenderId: '1060114483272',
    projectId: 'expenses-app-7f073',
    authDomain: 'expenses-app-7f073.firebaseapp.com',
    storageBucket: 'expenses-app-7f073.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHmVHgQpDu5Qi-q_MU0XXDnLO9opQj6l4',
    appId: '1:1060114483272:android:69028125b15a31f856f07d',
    messagingSenderId: '1060114483272',
    projectId: 'expenses-app-7f073',
    storageBucket: 'expenses-app-7f073.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfARA9gYiFWDnz7EjjNLzkuhEjnOqGWSs',
    appId: '1:1060114483272:web:37b19bd55b965d9256f07d',
    messagingSenderId: '1060114483272',
    projectId: 'expenses-app-7f073',
    authDomain: 'expenses-app-7f073.firebaseapp.com',
    storageBucket: 'expenses-app-7f073.firebasestorage.app',
  );
}
